import type { Metadata } from 'next'
import './globals.css'
import StoreProvider from '@/store/StoreProvider'
import { ApolloWrapper } from '@/apollos/client'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={''}>
        <div className="App">
          <StoreProvider>
            <ApolloWrapper>
              {children}
            </ApolloWrapper>
          </StoreProvider>
        </div>
      </body>
    </html>
  )
}
