import Progress from '@/components/prosses'
import type { Metadata } from 'next'
import styles from '../page.module.css'

export const metadata: Metadata = {
	title: 'Quizzes',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {

	return (
		<div className={styles.quiz}>
			<Progress />
			{children}
		</div>
	)
}
